version: '3'
services:
   php-fpm:
     build: 
      args:
        user: www-data
        uid: 1000
      context: ./docker/php
     container_name: php8-fpm
     environment:
      XDEBUG_MODE: develop,coverage,debug,profile
     extra_hosts:
      - "host.docker.internal:host-gateway"
     volumes:
       - ./:/var/www/
       - ./docker/php/config/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
       - ./docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
     networks:
      - netAuditto

   nginx:
     build: ./docker/nginx
     restart: always
     ports:
       - "80:80"
     volumes:
       - "./:/var/www/"
       - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
     depends_on:
       - php-fpm
     networks:
      - netAuditto

   db:
     image: mysql:8.0
     container_name: mysql
     command: --default-authentication-plugin=mysql_native_password
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: auditto
     ports:
      - 3306:3306
     volumes:
       - "./db:/var/lib/mysql"
     networks:
      - netAuditto

   adminer:
     image: adminer
     restart: always
     networks:
      - netAuditto
     ports:
       - 8080:8080

networks:
  netAuditto:
    driver: bridge